/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.KeyEvent;
import Control.*;
import Model.AddDeliveryManDa;
import Model.deliveryMan;
import javax.swing.JOptionPane;


public class AddDeliveryMan extends javax.swing.JFrame {

    
  
    public AddDeliveryMan() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Add Delivery Man");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jblHeading = new javax.swing.JLabel();
        jblName = new javax.swing.JLabel();
        jblIcNo = new javax.swing.JLabel();
        jblContactNo = new javax.swing.JLabel();
        jblAddress = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jtfIcNo = new javax.swing.JTextField();
        jblGuidance = new javax.swing.JLabel();
        jtfContoctNo = new javax.swing.JTextField();
        jtfAddress = new javax.swing.JTextField();
        jbtOK = new javax.swing.JButton();
        jbtReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jblHeading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblHeading.setText("Add Delivery Man");

        jblName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jblName.setText("Name");

        jblIcNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jblIcNo.setText("Ic No");

        jblContactNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jblContactNo.setText("Contact No");

        jblAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jblAddress.setText("Address");

        jtfName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNameKeyPressed(evt);
            }
        });

        jtfIcNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfIcNoKeyPressed(evt);
            }
        });

        jblGuidance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jblGuidance.setText("Insert Personal Detail");

        jtfContoctNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfContoctNoKeyPressed(evt);
            }
        });

        jbtOK.setText("OK");
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });

        jbtReset.setText("Reset");
        jbtReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtResetActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/backbutton.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblName)
                            .addComponent(jblIcNo))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfName)
                            .addComponent(jtfIcNo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblContactNo)
                            .addComponent(jblAddress))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfContoctNo)
                            .addComponent(jtfAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(99, 99, 99)
                                .addComponent(jbtOK, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(jbtReset, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jblGuidance))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jblGuidance, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblName)
                    .addComponent(jblContactNo)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfContoctNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblAddress)
                    .addComponent(jblIcNo)
                    .addComponent(jtfIcNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtOK, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtReset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed

        //retrieve all detail from the GUI
        deliveryMan deliveryMan = new deliveryMan();
        deliveryMan.setContactNo(jtfContoctNo.getText());
        deliveryMan.setAddress(jtfAddress.getText());
        deliveryMan.setIcNo(jtfIcNo.getText());
        deliveryMan.setName(jtfName.getText());
       
        //check field are filled
        
        
        //processes of ADT
        AddDeliveryManInterface addMan = new Control.AddDeliveryMan();
        
        //generate deliveryMan Code and set the initiate status
       deliveryMan.setDeliveryManId(addMan.generateDeliveryManId());
       deliveryMan.setStatus("Available");
        deliveryMan.setLevel("1");
        
        //update to linked List
         boolean result = HomePage.d.add(deliveryMan); // mylist is using a array please change it into linked list then should be ok
        
        //update to the showDeliveryMan table
        ShowDeliveryMan.DeliveryManTableModel.fireTableDataChanged();
        
        //Add to Database
//        AddDeliveryManDa addDeliveryManDa = new AddDeliveryManDa();
//        int result = addDeliveryManDa.addDeliveryMan(deliveryMan);
//        
//        //print out the result where success or not
        if(result)
            JOptionPane.showMessageDialog(null, "1 row(s) record have succeed added into Linked List","Success",JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(null, "1 row(s) record have failed added into Linked List","Failed",JOptionPane.ERROR_MESSAGE);
        
        //Clear Screen
        clearTextField();
        
        //close database connection
       // addDeliveryManDa.shutDown();
    }//GEN-LAST:event_jbtOKActionPerformed

    private void jtfNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNameKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            jtfIcNo.requestFocus();
    }//GEN-LAST:event_jtfNameKeyPressed

    private void jtfIcNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIcNoKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            jtfContoctNo.requestFocus();
    }//GEN-LAST:event_jtfIcNoKeyPressed

    private void jtfContoctNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfContoctNoKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            jtfAddress.requestFocus();
    }//GEN-LAST:event_jtfContoctNoKeyPressed

    private void clearTextField(){
         jtfAddress.setText("");
        jtfContoctNo.setText("");
        jtfIcNo.setText("");
        jtfName.setText("");
        jtfName.requestFocus();
    }
    private void jbtResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtResetActionPerformed

        clearTextField();
       
    }//GEN-LAST:event_jbtResetActionPerformed


    public static void main(String args[]) {
   
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDeliveryMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDeliveryMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDeliveryMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDeliveryMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDeliveryMan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jblAddress;
    private javax.swing.JLabel jblContactNo;
    private javax.swing.JLabel jblGuidance;
    private javax.swing.JLabel jblHeading;
    private javax.swing.JLabel jblIcNo;
    private javax.swing.JLabel jblName;
    private javax.swing.JButton jbtOK;
    private javax.swing.JButton jbtReset;
    private javax.swing.JTextField jtfAddress;
    private javax.swing.JTextField jtfContoctNo;
    private javax.swing.JTextField jtfIcNo;
    private javax.swing.JTextField jtfName;
    // End of variables declaration//GEN-END:variables
}
