package View;


import Model.food;
import java.util.ArrayList;
import java.util.List;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gan
 */
public class CDisplayResMenu extends javax.swing.JFrame {
    
     List<food> menuItem = new ArrayList<>();
String customerId ;
    
    public CDisplayResMenu(String customerId) {
        initComponents();
        this.customerId = customerId;
        jtfCustomerId.setText(customerId);
       jlblResName.setText(SelectRest.selectedResName);
        jtfCustomerId.setEditable(false);
        populateTable();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public void populateTable(){
    // This function to insert data into table first
    food menu = new food("Chicken Chop",15,0);
    food menu1 = new food("Fish Chop",15,0);
  food menu2 = new food("Pork Chop",15,0);
   menuItem.add(menu);
   menuItem.add(menu1);
    menuItem.add(menu2);
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    for(int i=0;i<RestaurantHome.stackFood.getNumberOfEntries();i++){
    //if(SelectRest.selectedResName.equals(RestaurantHome.stackFood.displayStack(i+1).getResName())){
    Object rowData[] = new Object[3];
    if(HomePage.listR.getEntry(SelectRest.selectedResIndex +1).getResName().equals(RestaurantHome.stackFood.displayStack(i+1).getResName())){
         rowData[0] = RestaurantHome.stackFood.displayStack(i+1).getFoodName();
        rowData[1] = RestaurantHome.stackFood.displayStack(i+1).getPrice();
       rowData[2] = 0;
        model.addRow(rowData);
    /*for(i=0;i<RestaurantHome.stackFood.getNumberOfEntries();i++){
        rowData[0] = RestaurantHome.stackFood.displayStack(i+1).getFoodName();
        rowData[1] = RestaurantHome.stackFood.displayStack(i+1).getPrice();
       // rowData[2] = menuItem.get(i).getQuantity();
       rowData[2] = 0;
        model.addRow(rowData);
    }*/
    }
    }
    //menuItem.clear();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jlblResName = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jtfCustomerId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food Name", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jlblResName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblResName.setText("LOL WESTERN FOOD");

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtfCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jlblResName, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblResName, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jtfCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //display the selected item on nxt jFrame
        TableModel model = jTable1.getModel();
        int indexs[] = jTable1.getSelectedRows();
       
        
        Object[] Row = new Object[4];
        
        PlaceOrder pOder = new PlaceOrder();
        DefaultTableModel model2 = (DefaultTableModel)pOder.jTable1.getModel();
        
        for(int i =0; i<indexs.length; i++){
            
            
          Row[0] = model.getValueAt(indexs[i],0); 
          Row[1] = model.getValueAt(indexs[i],1); 
          double a = (double) model.getValueAt(indexs[i],1);
          Row[2] = model.getValueAt(indexs[i],2);
          double b =(double) model.getValueAt(indexs[i],2);
          Row[3] = a*b; //subtotal
          
          
          model2.addRow(Row);
        
          
        }
               pOder.jTextField5.setText(this.jtfCustomerId.getText());
               pOder.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new SelectRest().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CDisplayResMenu("C00001").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlblResName;
    public static javax.swing.JTextField jtfCustomerId;
    // End of variables declaration//GEN-END:variables
}
