/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import ADT.DeliverymanADT;
import ADT.DeliverymanInterface;
import ADT.DeliverymanList;
import javax.swing.JFrame;

/**
 *
 * @author User
 */
public class MainMenuGUI extends javax.swing.JFrame {

    public static DeliverymanADT<DeliverymanInterface> dmList = new DeliverymanList<DeliverymanInterface>();
    /**
     * Creates new form MainMenuGUI
     */
    public MainMenuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        butDisplay = new javax.swing.JButton();
        butClockinout = new javax.swing.JButton();
        butAssign = new javax.swing.JButton();
        butTrack = new javax.swing.JButton();
        butChangeStatus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jButton5.setText("Display Deliverymen");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("- Main Menu Screen -");

        butDisplay.setText("Display Deliveryman");
        butDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDisplayActionPerformed(evt);
            }
        });

        butClockinout.setText("Clock In / Out");
        butClockinout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butClockinoutActionPerformed(evt);
            }
        });

        butAssign.setText("Assign Delivery Jobs");
        butAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAssignActionPerformed(evt);
            }
        });

        butTrack.setText("Track Order");
        butTrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTrackActionPerformed(evt);
            }
        });

        butChangeStatus.setText("Change Status");
        butChangeStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butChangeStatusActionPerformed(evt);
            }
        });

        jButton1.setText("Add Deliveryman");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butClockinout, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butTrack, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(butDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butChangeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butChangeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butClockinout, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butTrack, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDisplayActionPerformed
        DisplayDeliverymanGUI disGUI= new DisplayDeliverymanGUI();
        disGUI.setVisible(true);
        disGUI.setSize (500, 500);
        disGUI.setLocation (200, 100);
        disGUI.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_butDisplayActionPerformed

    private void butClockinoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butClockinoutActionPerformed
        ClockInOutGUI cGUI= new ClockInOutGUI();
        cGUI.setVisible(true);
        cGUI.setSize (500, 500);
        cGUI.setLocation (200, 100);
        cGUI.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_butClockinoutActionPerformed

    private void butChangeStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butChangeStatusActionPerformed
        ChangeStatusGUI chgGUI= new ChangeStatusGUI();
        chgGUI.setVisible(true);
        chgGUI.setSize (500, 500);
        chgGUI.setLocation (200, 100);
        chgGUI.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_butChangeStatusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddDeliverymanGUI addGUI= new AddDeliverymanGUI();
        addGUI.setVisible(true);
        addGUI.setSize (500, 500);
        addGUI.setLocation (200, 100);
        addGUI.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void butAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAssignActionPerformed
        AssignDeliveryJobGUI assGUI= new AssignDeliveryJobGUI();
        assGUI.setVisible(true);
        assGUI.setSize (500, 500);
        assGUI.setLocation (200, 100);
        assGUI.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_butAssignActionPerformed

    private void butTrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTrackActionPerformed
        TrackOrderGUI tGUI= new TrackOrderGUI();
        tGUI.setVisible(true);
        tGUI.setSize (500, 500);
        tGUI.setLocation (200, 100);
        tGUI.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_butTrackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAssign;
    private javax.swing.JButton butChangeStatus;
    private javax.swing.JButton butClockinout;
    private javax.swing.JButton butDisplay;
    private javax.swing.JButton butTrack;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
