/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.LListR;
import Control.LStackR;
import Model.MenuItem;
import Model.food;
import Model.menu;

/**
 *
 * @author Wei Kit
 */
public class RestaurantHome extends javax.swing.JFrame {

   //public static LStackR<MenuItem> stack = new LStackR<>();
   public static LStackR<food> stackFood = new LStackR<>();
   public static LStackR<menu> stackMenu = new LStackR<>();
   public static LListR<MenuItem> listMenu = new LListR<>();
    public RestaurantHome() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Select Function");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtAddMenu = new javax.swing.JButton();
        jbtViewMenu = new javax.swing.JButton();
        jbtUpdateMenu = new javax.swing.JButton();
        jbtRemoveMenu = new javax.swing.JButton();
        jbtBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtAddMenu.setText("Add Menu");
        jbtAddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddMenuActionPerformed(evt);
            }
        });

        jbtViewMenu.setText("View Menu Item");
        jbtViewMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtViewMenuActionPerformed(evt);
            }
        });

        jbtUpdateMenu.setText("Update Menu Item");
        jbtUpdateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUpdateMenuActionPerformed(evt);
            }
        });

        jbtRemoveMenu.setText("Remove Menu Item");
        jbtRemoveMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoveMenuActionPerformed(evt);
            }
        });

        jbtBack.setText("Back To Homepage");
        jbtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtAddMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtViewMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtUpdateMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtRemoveMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jbtAddMenu)
                .addGap(34, 34, 34)
                .addComponent(jbtViewMenu)
                .addGap(29, 29, 29)
                .addComponent(jbtUpdateMenu)
                .addGap(26, 26, 26)
                .addComponent(jbtRemoveMenu)
                .addGap(18, 18, 18)
                .addComponent(jbtBack)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddMenuActionPerformed
        dispose();
        new AddMenuItem().setVisible(true);
    }//GEN-LAST:event_jbtAddMenuActionPerformed

    private void jbtViewMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtViewMenuActionPerformed
        dispose();
        new ViewFood().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtViewMenuActionPerformed

    private void jbtRemoveMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoveMenuActionPerformed
        dispose();
        new RemoveMenuItem().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtRemoveMenuActionPerformed

    private void jbtUpdateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUpdateMenuActionPerformed
        dispose();
        new UpdateMenu().setVisible(true);
    }//GEN-LAST:event_jbtUpdateMenuActionPerformed

    private void jbtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBackActionPerformed
         dispose();
         new HomePage().setVisible(true);
    }//GEN-LAST:event_jbtBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtAddMenu;
    private javax.swing.JButton jbtBack;
    private javax.swing.JButton jbtRemoveMenu;
    private javax.swing.JButton jbtUpdateMenu;
    private javax.swing.JButton jbtViewMenu;
    // End of variables declaration//GEN-END:variables
}
