/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.myList;
import Model.DeliveryManTableModel;
import Model.deliveryMan;
import javax.swing.JOptionPane;

import javax.swing.ListSelectionModel;

/**
 *
 * @author Asus
 */
public class ShowDeliveryMan extends javax.swing.JFrame {

  public static DeliveryManTableModel DeliveryManTableModel = new DeliveryManTableModel();
    
    public ShowDeliveryMan(myList<deliveryMan> d) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Show Delivery Man brief");
       jTable2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jblDeliveryManID = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jtfDeliveryManId = new javax.swing.JTextField();
        jtfDeliveryManName = new javax.swing.JTextField();
        jbtFilter = new javax.swing.JButton();
        String[] level = {"Level 1","Level 2","Level 3"};
        jcbDeliveryManLevel = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jbtDailyReport = new javax.swing.JButton();
        jbtPendingDeliveries = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Show Delivery Man");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Insert detail to filter:");

        jblDeliveryManID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jblDeliveryManID.setText("Delivery Man ID:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Delivery Man Name:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Delivery Man Level:");

        jtfDeliveryManId.setToolTipText("Enter Delivery Man ID");

        jbtFilter.setText("Filter");
        jbtFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFilterActionPerformed(evt);
            }
        });

        jcbDeliveryManLevel.setModel(new javax.swing.DefaultComboBoxModel<>(level));

        jTable2.setModel(DeliveryManTableModel);
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("Registration");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Retrieve");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jbtDailyReport.setText("Daily Report");
        jbtDailyReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDailyReportActionPerformed(evt);
            }
        });

        jbtPendingDeliveries.setText("Pending Deliveries");
        jbtPendingDeliveries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPendingDeliveriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(20, 20, 20)
                        .addComponent(jButton4)
                        .addGap(42, 42, 42)
                        .addComponent(jButton3)
                        .addGap(33, 33, 33)
                        .addComponent(jbtDailyReport)
                        .addGap(35, 35, 35)
                        .addComponent(jbtPendingDeliveries))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jblDeliveryManID)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfDeliveryManName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfDeliveryManId, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbDeliveryManLevel, 0, 131, Short.MAX_VALUE))
                        .addGap(57, 57, 57)
                        .addComponent(jbtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblDeliveryManID)
                    .addComponent(jtfDeliveryManId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jcbDeliveryManLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtFilter))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jbtDailyReport)
                            .addComponent(jbtPendingDeliveries)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfDeliveryManName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFilterActionPerformed

        
      //  int index = jcbDeliveryManLevel.getSelectedIndex()+1; result if select lv1 will return 1 
        
    }//GEN-LAST:event_jbtFilterActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

         int rowIndex = jTable2.getSelectedRow();
        if(rowIndex == -1)
            JOptionPane.showMessageDialog(null, "Please Select a Row From Table to Retrieve Detail.","ERROR",JOptionPane.ERROR_MESSAGE);
        else{
            
            String name =(String) jTable2.getValueAt(rowIndex, 1);
           int result = JOptionPane.showConfirmDialog(null, "Are you sure to remove "+name+" from system?","ARE YOU SURE?",JOptionPane.OK_OPTION);
           if(result == JOptionPane.OK_OPTION){
               HomePage.deliveryMan.remove(rowIndex+1);
               DeliveryManTableModel.fireTableDataChanged();
           }
            
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 
        int rowIndex = jTable2.getSelectedRow();
        if(rowIndex == -1)
            JOptionPane.showMessageDialog(null, "Please Select a Row From Table to Retrieve Detail.","ERROR",JOptionPane.ERROR_MESSAGE);
        else{
            String id = (String) jTable2.getValueAt(rowIndex, 0);
            new DeliveryInformation(rowIndex+1).setVisible(true);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int rowIndex = jTable2.getSelectedRow();
        if(rowIndex == -1)
            JOptionPane.showMessageDialog(null, "Please Select a Row From Table to Update.","ERROR",JOptionPane.ERROR_MESSAGE);
        else{
            //String id = (String)jTable2.getValueAt(rowIndex, 0);
            //JOptionPane.showMessageDialog(null, rowIndex);
            //JOptionPane.showMessageDialog(null, rowIndex+1);
        new UpdateDeliverymanInformation(rowIndex+1).setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        new AddDeliveryMan().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtPendingDeliveriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPendingDeliveriesActionPerformed
 
        if(HomePage.customer.isEmpty() && HomePage.order.isEmpty()){
               JOptionPane.showMessageDialog(this, "you havent create order and register as customer");
           
               
        }
        else if(HomePage.customer.isEmpty())
            JOptionPane.showMessageDialog(this, "you haven't create as customer");
        else if(HomePage.order.isEmpty())
             JOptionPane.showMessageDialog(this, "you haven't create an order yet");
        
        else if(!HomePage.customer.isEmpty()&&!HomePage.order.isEmpty()){
            new PendingDeliveries().setVisible(true);
        }
        
    }//GEN-LAST:event_jbtPendingDeliveriesActionPerformed

    private void jbtDailyReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDailyReportActionPerformed
 
        new DailyReport().setVisible(true);
    }//GEN-LAST:event_jbtDailyReportActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel jblDeliveryManID;
    private javax.swing.JButton jbtDailyReport;
    private javax.swing.JButton jbtFilter;
    private javax.swing.JButton jbtPendingDeliveries;
    private javax.swing.JComboBox<String> jcbDeliveryManLevel;
    private javax.swing.JTextField jtfDeliveryManId;
    private javax.swing.JTextField jtfDeliveryManName;
    // End of variables declaration//GEN-END:variables
}
